SHRUG_2011-04-13_PDF/pdfkittest/config/routes.rb
Pdfkittest::Application.routes.draw do
  resources :horses

end

SHRUG_2011-04-13_PDF/pdfkittest/app/models/horse.rb
class Horse < ActiveRecord::Base
end

SHRUG_2011-04-13_PDF/pdfkittest/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

SHRUG_2011-04-13_PDF/pdfkittest/app/controllers/horses_controller.rb
class HorsesController < ApplicationController
  # GET /horses
  # GET /horses.xml
  def index
    @horses = Horse.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @horses }
    end
  end

  # GET /horses/1
  # GET /horses/1.xml
  def show
    @horse = Horse.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @horse }
    end
  end

  # GET /horses/new
  # GET /horses/new.xml
  def new
    @horse = Horse.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @horse }
    end
  end

  # GET /horses/1/edit
  def edit
    @horse = Horse.find(params[:id])
  end

  # POST /horses
  # POST /horses.xml
  def create
    @horse = Horse.new(params[:horse])

    respond_to do |format|
      if @horse.save
        format.html { redirect_to(@horse, :notice => 'Horse was successfully created.') }
        format.xml  { render :xml => @horse, :status => :created, :location => @horse }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @horse.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /horses/1
  # PUT /horses/1.xml
  def update
    @horse = Horse.find(params[:id])

    respond_to do |format|
      if @horse.update_attributes(params[:horse])
        format.html { redirect_to(@horse, :notice => 'Horse was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @horse.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /horses/1
  # DELETE /horses/1.xml
  def destroy
    @horse = Horse.find(params[:id])
    @horse.destroy

    respond_to do |format|
      format.html { redirect_to(horses_url) }
      format.xml  { head :ok }
    end
  end
end

SHRUG_2011-04-13_PDF/pdfkittest/app/helpers/application_helper.rb
module ApplicationHelper
end

SHRUG_2011-04-13_PDF/pdfkittest/app/helpers/horses_helper.rb
module HorsesHelper
end

SHRUG_2011-04-13_PDF/pdfkittest/app/views/horses/_form.html.erb
<%= form_for(@horse) do |f| %>
  <% if @horse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@horse.errors.count, "error") %> prohibited this horse from being saved:</h2>

      <ul>
      <% @horse.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :breed %><br />
    <%= f.text_field :breed %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SHRUG_2011-04-13_PDF/pdfkittest/app/views/horses/edit.html.erb
<h1>Editing horse</h1>

<%= render 'form' %>

<%= link_to 'Show', @horse %> |
<%= link_to 'Back', horses_path %>

SHRUG_2011-04-13_PDF/pdfkittest/app/views/horses/index.html.erb
<h1>Listing horses</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Breed</th>
    <th>Gender</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @horses.each do |horse| %>
  <tr>
    <td><%= horse.name %></td>
    <td><%= horse.age %></td>
    <td><%= horse.breed %></td>
    <td><%= horse.gender %></td>
    <td><%= link_to 'Show', horse %></td>
    <td><%= link_to 'Edit', edit_horse_path(horse) %></td>
    <td><%= link_to 'Destroy', horse, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Horse', new_horse_path %>

SHRUG_2011-04-13_PDF/pdfkittest/app/views/horses/new.html.erb
<h1>New horse</h1>

<%= render 'form' %>

<%= link_to 'Back', horses_path %>

SHRUG_2011-04-13_PDF/pdfkittest/app/views/horses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @horse.name %>
</p>

<p>
  <b>Age:</b>
  <%= @horse.age %>
</p>

<p>
  <b>Breed:</b>
  <%= @horse.breed %>
</p>

<p>
  <b>Gender:</b>
  <%= @horse.gender %>
</p>


<%= link_to 'Edit', edit_horse_path(@horse) %> |
<%= link_to 'Back', horses_path %>

SHRUG_2011-04-13_PDF/pdfkittest/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pdfkittest</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>